name: Build

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_ARCH: x86

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]

    steps:
      - name: Install Linux packages
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -yq --no-install-recommends gcc-multilib g++-multilib

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: extension
          submodules: recursive

      - name: Checkout AMBuild
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/ambuild
          path: ambuild

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies and ambuild
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install ./ambuild

      - name: Build
        working-directory: extension
        shell: bash
        run: |
          unzip -qq boost.zip
          unzip -qq openssl.zip
          mkdir build && cd build
          perl ../curl/lib/mk-ca-bundle.pl
          python ../configure.py --enable-optimize --targets=${{env.BUILD_ARCH}} --sm-path ../sourcemod
          ambuild

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: extension/build/package

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Package
        run: |
          echo version=$GITHUB_REF | sed "s/refs\/tags\///" >> $GITHUB_ENV
          7z a sm-ripext-${{env.version}}-ubuntu-20.04.zip ./ubuntu-20.04/*
          7z a sm-ripext-${{env.version}}-windows-2019.zip ./windows-2019/*

      - name: Upload Release File
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.zip'
          tag: ${{ github.ref }}
          file_glob: true